AppwriteException: User (role: guests) missing scope (account)     at Client.<anonymous> (https://6000-firebase-studio-1748670559211.cluster-isls3qj2gbd5qs4jkjqvhahfv6.cloudworkstations.dev/_next/static/chunks/node_modules_7e44694d._.js:9480:27)     at Generator.next (<anonymous>)     at fulfilled (https://6000-firebase-studio-1748670559211.cluster-isls3qj2gbd5qs4jkjqvhahfv6.cloudworkstations.dev/_next/static/chunks/node_modules_7e44694d._.js:9072:32)